import "./globals.css";
import {CssBaseline, ThemeProvider } from '@mui/material';
import theme from './defaultTheme.js';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body>
      <ThemeProvider theme={theme}>
      <CssBaseline />
      <h3 className="logo">인터뷰닷</h3>
      <div className="bg">
      {children}
      </div>
      </ThemeProvider>
      </body>
    </html>
  );
}
