import "./globals.css";
import {CssBaseline, ThemeProvider } from '@mui/material';
import theme from './defaultTheme.js';
import Header from "./header/page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className="body1">
      <ThemeProvider theme={theme}>
      <CssBaseline />
      <Header />
      <div className="bg">
      {children}
      </div>
      </ThemeProvider>
      </body>
    </html>
  );
}
